<?php
namespace SinticBolivia\SBFramework\Modules\Invoices\Classes\Siat;

class DocumentTypes
{
	const FACTURA_COMPRA_VENTA = 1;
	const FACTURA_ALQUILER_INMUEBLES = 2;
	const FACTURA_COMERCIAL_EXPORTACION = 3;
	const FACTURA_COMERCIAL_EXPORTACION_LIBRE_CONSIGNACION = 4;
	const FACTURA_VENTA_ZONA_FRANCA = 5;
	const FACTURA_SERVICIO_TURISTICO = 6;
	const FACTURA_SEG_ALIMENTARIA = 7;
	const FACTURA_TASA_CERO_LIBROS = 8;
	const FACTURA_COMPRA_VENTA_MONEDA_EXTRAJERA = 9;
	const FACTURA_DUTTY_FREE = 10;
	const FACTURA_SECTOR_EDUCATIVO = 11;
	const FACTURA_COM_HIDROCARBUROS = 12;
	const FACTURA_SERV_BASICOS = 13;
	const FACTURA_PRODS_ICE = 14;
	const FACTURA_ENT_FINANCIERA = 15;
	const FACTURA_HOTELES = 16;
	const FACTURA_HOSPITALES = 17;
	const FACTURA_JUEGOS_AZAR = 18;
	const FACTURA_HIDROCARBUROS = 19;
	const FACTURA_EXPORT_MINERALES = 20;
	const FACTURA_VENTA_MINERALES = 21;
	const FACTURA_TELECOMUNICACIONES = 22;
	const FACTURA_PREVALORADA = 23;
	const FACTURA_NOTA_CRED_DEB = 24;
	const FACTURA_COM_EXPORT_SERVICIOS = 28;
	const FACTURA_NOTA_CONCILIACION = 29;
	const FACTURA_BOLETO_AEREO = 30;
	const FACTURA_SUMIN_ENERGIA = 31;
	const FACTURA_ICE_ZONA_FRANCA = 32; 
	
}